- src/components/CourseRegister/index.tsx
- src/components/common/Modal/InfoModal.tsx
- src/components/common/Modal/LoadingModal.tsx
- src/components/common/Modal/WaitingModal.tsx
- src/pages/index/Home.tsx
- src/store/courseRegisteredSlice.ts
- src/store/store.ts
- #60 
- 수강신청 로직을 LoadingModal로 옮겼습니다.
- 17초가 지나면 모든과목 수강신청 실패가 뜹니다.
- 17초 이내여도 10%의 확률로 수강신청 실패가 뜹니다.
[이 커밋 확인하시면 됩니다!](https://github.com/tutorial-sejong/cr-frontend/pull/65/commits/9b3c4f02a0fa611538658d7010bc8e2e7fa56c84)
> feat: 수강신청 실패 추가

- src/components/common/Modal/ErrorModal.tsx
- src/pages/index/Home.tsx
- #67 
- ErrorModal로 분리하였습니다.
- type과 errorField props 이용하여 사용하시면 됩니다.
```js
const errorMessage = () => {
switch (type) {
case 404:
return '조회된 내역이 없습니다.';
case 409:
return '이미 신청된 정보가 존재하므로 신청할 수 없습니다.';
case 410:
return '수강여석이 없습니다!';
case 422:
switch (errorField) {
case '교수명':
return '강의 교수명은 2자 이상 반드시 입력하십시오!';
case '교과목명':
return '교과목명은 2자 이상 반드시 입력하십시오!';
case '학수번호':
return '학수번호를 정확하게 입력하십시오!';
case '분반':
return '분반을 정확하게 입력하십시오!';
default:
return '422 알 수 없는 오류';
}
default:
return '알 수 없는 오류';
}
};
```
> refactor: modal 리팩토링

- src/components/Wishlist/Filters.tsx
- #72
- 관심과목 필터에서 에러인 상황에도 그냥 검색이 되는 버그를 해결했습니다.
> fix: 관심과목 필터 버그 해결

- package-lock.json
- package.json
- src/App.tsx
- src/components/LoginForm/index.tsx
- src/components/common/FilterButton.tsx
- src/pages/index/Login.tsx
> chore: 구글 애널리틱스 설정

- src/components/DeleteAccount/DeleteAccountForm.tsx
> fix: 학번 타입 에러 수정

- src/components/Header/TopMenu.tsx
- src/components/Header/index.tsx
- src/components/Menubar/index.tsx
- src/pages/index/Home.tsx
> refactor: 디자인 수정

- src/apis/api/course.ts
- src/components/Wishlist/index.tsx
- 바뀐 post `/wishlist/save` api에 맞춰 리스트가 아닌 scheduleId를 사용해 관심과목 담기를 하도록 변경했습니다.
> refactor: 관심과목 담기 api 사용 리팩토링

- src/components/common/Modal/LoadingModal.tsx
- #86 
기존: 1 ~ 3초
수정: 0.5초 ~ 1초
> refactor: 로딩 모달 시간 수정

- src/pages/index/Login.tsx
> refactor: 개인 정보 수집 안내 수정

- src/pages/index/Login.tsx
> fix: delete 페이지 navigate 설정

- src/App.tsx
- src/components/Header/TopMenu.tsx
- src/components/LoginForm/index.tsx
- src/pages/index/Home.tsx
- src/pages/index/NotFound.tsx
- src/store/modules/tabSlice.ts
- [TS-23](https://jeez.atlassian.net/browse/TS-23?atlOrigin=eyJpIjoiODI4ODgzOWMxYzhkNDllMDlhYjYzODk0MDBjNDcyYzMiLCJwIjoiaiJ9)
- 잘못된 경로일 때 보여줄 에러 페이지를 만들었습니다.
- 로그인 후에 선택된 탭이 없는 오류를 해결했습니다.
- '본 사이트는 실제 수강신청 사이트가 아닙니다.' 알림을 로그인 후 홈으로 가기 전에 뜨도록 변경했습니다.
홈 화면 에서 띄우니까 알림창을 닫기 전까지 렌더링이 덜 되어 깨져 보이는 것들이 있어서 변경하게 되었습니다. 
[TS-23]: https://jeez.atlassian.net/browse/TS-23?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TS-23): 에러 페이지 생성

- src/main.tsx
- 불필요한 파일을 삭제하면서 확인하지 못한 import가 오류를 발생 시켜 정리했습니다.
> fix: import 오류 해결

- src/components/LoginForm/FormInput.tsx
- src/pages/index/Login.tsx
- src/styles/GlobalStyle.tsx
- #TS-33
- box-sizing을 설정하였습니다.
- 학번, 비밀번호 입력 칸에 padding을 넣었습니다.
> refactor(TS-33): 로그인 입력창 스타일 수정

- src/components/common/Modal/AntiMacroCodeModal.tsx
[TS-36](https://jeez.atlassian.net/browse/TS-36)
- 매크로 이미지 처리 로직 간소화
- 기존: 이미지 URL을 받아 추가 fetch 요청으로 이미지를 불러옴
- 변경: 서버로부터 받은 Base64 이미지를 직접 사용
- 백엔드에서 Base64로 인코딩된 이미지를 직접 전달하도록 변경됨에 따라, 프론트엔드의 이미지 처리 로직을 간소화하였습니다.
- 기존의 이미지 fetch, blob 변환, URL.createObjectURL 처리 과정을 제거하고, 서버에서 받은 Base64 이미지를 직접 사용하도록 변경하였습니다.
[TS-36]: https://jeez.atlassian.net/browse/TS-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(TS-36): 매크로 이미지 처리 로직 간소화

- src/components/CourseRegister/StartButton.tsx
- src/components/CourseRegister/index.tsx
- src/components/Header/TopMenu.tsx
- src/store/modules/courseRegisteredSlice.ts
- [TS-29](https://jeez.atlassian.net/browse/TS-29?atlOrigin=eyJpIjoiMzYxZjg0NWIwNTFmNDI4NmE4YjMyZjhmNWJiZjVkMzgiLCJwIjoiaiJ9)
- 분 : 초로 표시됩니다.
- 제한 시간 안내 문구를 추가했습니다.
- 빈 입력이나 기본 값(35초)을 수정하지 않을 경우 35초로 설정됩니다.
- 최대(1시간), 최소(10초) 시간을 벗어난 값을 입력하면 자동으로 최대/최소값으로 변경됩니다.
- 남은 시간이 5초 이하일 때에는 빨간색으로 출력 되도록 했습니다.
- courseRegisterSlice에 제한 시간 데이터를 추가했습니다.
- 로그아웃시 courseRegisterSlice안의 데이터를 초기화하도록 했습니다.
[TS-29]: https://jeez.atlassian.net/browse/TS-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TS-29): 제한 시간 기능 추가

- .gitignore
- netlify.toml
- package.json
- [TS-39](https://jeez.atlassian.net/browse/TS-39?atlOrigin=eyJpIjoiYjBjZDQ5YmM3NzUzNDZkMThmZTNmYjcyYzc1NWRjYmMiLCJwIjoiaiJ9)
- netlify.toml 설정 파일을 추가했습니다.
- 로컬에서 배포 테스트를 하기 위해 netlify cli를 사용하면서 .gitignore에 .netlify가 추가되었습니다.
[TS-39]: https://jeez.atlassian.net/browse/TS-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TS-39): 새로고침 시 page not found 에러 해결

- src/components/CourseRegister/InfoContent.tsx
- src/components/CourseRegister/index.tsx
- src/pages/index/Home.tsx
- [TS-40](https://jeez.atlassian.net/browse/TS-40?atlOrigin=eyJpIjoiZDU4MWZkNDUwYmU0NGQ5MTgyZDg2NThmYjE1YjhkM2IiLCJwIjoiaiJ9)
- 수강신청 안내문에서 수강신청 시작 페이지로 넘어갈때 스크롤 위치가 맨 위로 가도록 했습니다.
- 탭 매뉴바가 화면 사이즈에 따라 자동으로 닫히도록 수정하였습니다.
[TS-40]: https://jeez.atlassian.net/browse/TS-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(TS-40): 스크롤 위치 및 탭 매뉴 반응형 수정

- src/components/CourseRegister/InfoContent.tsx
- src/components/CourseRegister/RegisterInfo.tsx
- src/components/common/SelectBox.tsx
- [TS-44](https://jeez.atlassian.net/browse/TS-44?atlOrigin=eyJpIjoiYjJmZTM3Y2IyYTA3NDRkMzliNzA1YTZiMzNlMzc1NDkiLCJwIjoiaiJ9)
- 학과 선택 박스의 선택 옵션이 더 많이 보이도록 세로 길이를 늘렸습니다.
- 학과 검색 시 스크롤이 생기는 불편함을 해결하기 위해 안내문의 배치를 수정하였습니다.
- 학과 입력칸을 누르면 입력칸을 비우고 모든 옵션이 보이도록 하였습니다.
- 사용자 최적화를 위해 필터링 기능에 debounce를 적용하였습니다.
[TS-44]: https://jeez.atlassian.net/browse/TS-44?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(TS-44): 학과 선택 박스 사이즈 수정 및 검색 기능 최적화

- src/components/CourseRegister/RegisterFilters.tsx
- src/components/common/Modal/LoadingModal.tsx
- [TS-60](https://jeez.atlassian.net/browse/TS-60?atlOrigin=eyJpIjoiMzczMmUxZWM0N2E1NGY0YTliZjdjMGE0NjhmZTI1YzIiLCJwIjoiaiJ9)
- *fix: 로컬 환경에서 수강신청 요청을 중복으로 보내서 에러가 생기는 현상 해결
- 현재 서버에 요청 중인지 확인하여 한 번 만 보내도록 수정
- *refactor: 수강신청 필터 박스 css 수정
- 수정 전
- 수정 후
[TS-60]: https://jeez.atlassian.net/browse/TS-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TS-60): 수강신청 중복 요청 수정

- src/components/common/Table/TableHead.tsx
- src/components/common/Table/index.tsx
- [TS-63](https://jeez.atlassian.net/browse/TS-63?atlOrigin=eyJpIjoiNGQwZWZjZjI4OTMxNGM1NTgyN2E5MmE3MDE5ODdkZTYiLCJwIjoiaiJ9)
- 테이블의 필터가 너무 길어졌을 때 밑 부분이 잘리는 현상을 해결했습니다.
[TS-63]: https://jeez.atlassian.net/browse/TS-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TS-63): 테이블 필터 잘림 현상 해결

- src/apis/utils/instance.ts
- [TS-64](https://jeez.atlassian.net/browse/TS-64?atlOrigin=eyJpIjoiODM1OWY0ODFkYTVmNDg2YjgwNTBlOGIxMWE2NmZiZjQiLCJwIjoiaiJ9)
- 인증 관련 에러 코드들이 S->A로 시작하도록 변경되어 수정했습니다.
- A001, A003일 때는 로그아웃 후 로그인 페이지로 이동하게 했습니다.
[TS-64]: https://jeez.atlassian.net/browse/TS-64?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TS-64): 오류 코드 수정

- README.md
- [TS-50](https://jeez.atlassian.net/browse/TS-50?atlOrigin=eyJpIjoiNjg3NjVmMGI5NjQxNDM5ODlkZGE0MDMyOWIyMTgwMzAiLCJwIjoiaiJ9)
- 소개, 개요, 기능, 화면, 디렉토리 구조를 수정했습니다.
[TS-50]: https://jeez.atlassian.net/browse/TS-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(TS-50): 리드미 업데이트

- src/components/Wishlist/Filters.tsx
- [TS-65](https://jeez.atlassian.net/browse/TS-65?atlOrigin=eyJpIjoiZjdiYjQyMjc1ZDUyNGU0ZWE2NzFlMDg4MGIxMTI5YmMiLCJwIjoiaiJ9)
- 2024/2학기 -> 2025/1학기 업데이트
[TS-65]: https://jeez.atlassian.net/browse/TS-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: 학기 시간 업데이트
